name: quality-quests
version: ${project.version}
author: philip2096
description: A simple zero config quest plugin
main: com.github.philipkoivunen.quality_quests.QualityQuestsPlugin
depend:
  - trollskogen-core
  - CoreProtect
api-version: 1.15
commands:
  qquests:
  quests:
permissions:
  qualityquests.quest.quests:
    default: false
  qualityquests.quest.epicQuests:
    default: false
  qualityquests.quest.reload:
    default: false