name: quality-quests
version: ${project.version}
author: philip2096
description: A simple zero config quest plugin
main: com.github.philipkoivunen.quality_quests.QualityQuestsPlugin
depend: []
api-version: 1.15
commands:
  trail:
permissions:
  qualityquests.quest.quests:
    default: false
  qualityquests.quest.epicQuests:
    default: false
  qualityquests.quest.reload:
    default: false