package com.github.philipkoivunen.quality_quests.constants;

public enum MessageConstants {
    NO_PERMISSION,
    MISSING_ARGUMENT,
    DEFAULT_ERROR,
    CONFIGURATION_RELOAD_SUCCESS,
    CONFIGURATION_RELOAD_FAILURE,
    CREATE_QUEST_FAILED_PARAM,
    CREATE_QUEST_SUCCESS,
    LIST_QUESTS_TITLE,
    LIST_QUEST_KILL,
    LIST_QUEST_BREAK,
    LIST_QUEST_CUSTOM,
    LIST_QUEST_EMPTY,
    SET_MOB_FAILURE_PARAM,
    UPDATE_QUEST_ERROR,
    UPDATE_QUEST_SUCCESS,
    START_QUEST_SUCCESS,
    START_QUEST_FAILURE,
    QUEST_ACTIVATE_HANDLER_ERROR,
    QUEST_COMPLETED,
    QUEST_PROGRESSED;
}
